server:
  port: 8081
spring:
  application:
    name: serverDataBaseApplication
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.230.228:8848
  datasource:
    url: jdbc:mysql://1.15.230.228/server_monitor_data?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 402414521
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 1.15.230.228
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: 402414521a

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

