spring:
  redis:
    host: 1.15.xxx.228
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
    password: xxx




